stages:
- build
- test
- cleanup

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  # pin to specific docker images for build repeatability
  #points registry.gitlab.syncad.com/hive/hive/runtime:ubuntu-20.04-3
  RUNTIME_IMAGE_TAG: "@sha256:58b2ef26ece0463bad9ba61c665ffb9dc4255a4d65b27f56048786e3fae7b2e5"
  #points registry.gitlab.syncad.com/hive/hive/builder:ubuntu-20.04-3
  BUILDER_IMAGE_TAG: "@sha256:590750387c74c470ee30910502b4f855122eae9ef9c6e7ad0841985abdc3938c"
  #points registry.gitlab.syncad.com/hive/hive/test:ubuntu-20.04-3
  TEST_IMAGE_TAG: "@sha256:991f5c225ea66dccabd43ae18ebe9cc4c90dc2b14d80625202f96e041c832ac6"

include: '/scripts/ci-helpers/prepare_data_image_job.yml'

prepare_hived_data_image:
  extends: .prepare_hived_data_5m_image
  stage: build
  variables:
    REGISTRY_USER: "$HIVED_CI_IMGBUILDER_USER"
    REGISTRY_PASS: $HIVED_CI_IMGBUILDER_PASSWORD

  tags:
    - public-runner-docker
    - hived-for-tests

cleanup_hived_data_image:
  extends: .docker_image_cleanup_job
  stage: cleanup
  dependencies:
    - prepare_hived_data_image

  variables:
    REGISTRY: $CI_REGISTRY_IMAGE
    REGISTRY_USER: "$HIVED_CI_IMGBUILDER_USER"
    REGISTRY_PASS: $HIVED_CI_IMGBUILDER_PASSWORD
    IMAGE_PATH: $HIVED_IMAGE_NAME_REGISTRY_PATH
    IMAGE_TAG: $HIVED_IMAGE_NAME_REGISTRY_TAG

  tags:
    - public-runner-docker
    - hived-for-tests

.test_tools_based:
  variables:
    HIVED_PATH: "$CI_PROJECT_DIR/testnet_node_build/install-root/bin/hived"
    CLI_WALLET_PATH: "$CI_PROJECT_DIR/testnet_node_build/install-root/bin/cli_wallet"
    GET_DEV_KEY_PATH: "$CI_PROJECT_DIR/testnet_node_build/install-root/bin/get_dev_key"
    TEST_TOOLS_NODE_DEFAULT_WAIT_FOR_LIVE_TIMEOUT: "60"
  before_script:
    - apt-get update -y && apt-get install -y python3 python3-pip python3-dev
    - export NUMBER_OF_PROCESSES=$(nproc)
    - pip3 install pytest pytest-xdist "$CI_PROJECT_DIR/tests/test_tools"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - "**/generated_during_*"
    - "**/generated_by_package_fixtures"
    when: always
    expire_in: 1 week

